version: '3'
services:
  bot:
    build: ./bot
    depends_on:
      - rabbit
      - gateway
  rabbit:
    image: rabbitmq:alpine
  timer:
    build: ./timer
    depends_on:
      - rabbit
  gateway:
    build: ./gateway
    depends_on:
      - rabbit
